name: sportapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  get: ^4.6.5
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  google_fonts:
  #  http: ^0.13.6
  provider: ^6.0.4
  action_slider: ^0.7.0
  animated_notch_bottom_bar: ^1.0.3
  logger: ^2.0.2+1
  dependency_validator: ^3.2.3
  #  flutter pub run dependency_validator
  dio: ^5.2.1+1
  #  dio: ^5.4.0
  go_router: ^13.0.0
  intl: any
  intl_phone_field: ^3.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  pinput: ^4.0.0
  geolocator: ^7.6.2
  geocoding: ^2.2.0
  qr_code_scanner:
  camera: ^0.11.0+1
  image_picker:
  flutter_google_places:
  cloud_firestore: ^4.14.0
  video_player: ^2.8.6
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^14.7.10
  circular_seek_bar: ^1.1.1
  card_swiper: ^3.0.1
  fluttertoast: ^8.2.6
  share_plus: ^10.0.0
  phone_input: ^1.0.0
  sliding_up_panel:
  google_maps_flutter: ^2.9.0
  flutter_bloc: ^8.1.6

  google_api_headers: any
  google_maps_webservice: any
  flutter_rating_bar: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.6.0 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  launcher_name: ^1.0.2

launcher_name:
  default: "LemakLand"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Images/icon.png"
  remove_alpha_ios: true

flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Mont-Heavy
      fonts:
        - asset: assets/fonts/Mont-Heavy.ttf
    - family: Mont-Light
      fonts:
        - asset: assets/fonts/Mont-Light.ttf
    - family: Mont-Medium
      fonts:
        - asset: assets/fonts/Mont-Bold.ttf
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay.ttf
#    - family: :clashDisplay-light
#      fonts:
#        _ asset:assets/fonts/ClashDisplayLight.otf
#    - family: :clashDisplay-Regular
#      fonts:
#        _ asset:assets/fonts/ClashDisplay-Regular.otf
#    - family: :clashDisplay-Medium
#      fonts:
#        _ asset:assets/fonts/ClashDisplay-Medium.otf
#    - family: :clashDisplay-Bold
#      fonts:
#        _ asset:assets/fonts/ClashDisplay-Bold.otf

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
